//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.11
//
// <auto-generated>
//
// Generated from file `calculator.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package sr.ice.Demo;

public class EmptyInput extends com.zeroc.Ice.UserException
{
    public EmptyInput()
    {
        this.reason = "Input cannot be empty";
    }

    public EmptyInput(Throwable cause)
    {
        super(cause);
        this.reason = "Input cannot be empty";
    }

    public EmptyInput(String reason)
    {
        this.reason = reason;
    }

    public EmptyInput(String reason, Throwable cause)
    {
        super(cause);
        this.reason = reason;
    }

    public String ice_id()
    {
        return "::Demo::EmptyInput";
    }

    public String reason;

    /** @hidden */
    @Override
    protected void _writeImpl(com.zeroc.Ice.OutputStream ostr_)
    {
        ostr_.startSlice("::Demo::EmptyInput", -1, true);
        ostr_.writeString(reason);
        ostr_.endSlice();
    }

    /** @hidden */
    @Override
    protected void _readImpl(com.zeroc.Ice.InputStream istr_)
    {
        istr_.startSlice();
        reason = istr_.readString();
        istr_.endSlice();
    }

    /** @hidden */
    public static final long serialVersionUID = -4227587782155386968L;
}
