# suppress inspection "SpringBootApplicationProperties" for whole file
spring.application.name=radar

# Switch between custom and Spring Security OAuth2 token management
opensky.api.token-management=custom
#opensky.api.token-management=spring-security
# -------- OpenSky --------

## OpenSky API credentials for Spring Boot Security OAuth2
spring.security.oauth2.client.registration.opensky.client-id=${CLIENT_ID}
spring.security.oauth2.client.registration.opensky.client-secret=${CLIENT_SECRET}
spring.security.oauth2.client.registration.opensky.scope=read
spring.security.oauth2.client.registration.opensky.authorization-grant-type=client_credentials

spring.security.oauth2.client.provider.opensky.token_uri=https://auth.opensky-network.org/auth/realms/opensky-network/protocol/openid-connect/token

# OpenSky API credentials for custom Token management
opensky.api.client-id=${CLIENT_ID}
opensky.api.client-secret=${CLIENT_SECRET}
opensky.api.token-url=https://auth.opensky-network.org/auth/realms/opensky-network/protocol/openid-connect/token
opensky.api.token-margin=15

#  -------- Aero Box API --------
aerobox.api.key=${AEROBOX_API_KEY}

# ------- Aviation Stack API --------
aviationstack.api.key=${STACK_API_KEY}