spring.application.name=rabbitmq-system
logging.pattern.console=%d{HH:mm:ss} %-5level %logger{15} - %msg%n
spring.rabbitmq.addresses=${RABBITMQ_HOST:localhost}:${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USER:admin}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:admin}
agency.id=${AGENCY_ID:1}

carrier.id=${CARRIER_ID:1}

carrier.people=${CARRIER_PEOPLE:true}
carrier.cargo=${CARRIER_CARGO:true}
carrier.satellite=${CARRIER_SATELITE:false}
